# Generated by Django 3.2.14 on 2022-08-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='邮箱')),
                ('note', models.TextField(blank=True, max_length=60, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='邮箱')),
                ('note', models.CharField(blank=True, max_length=60, null=True, verbose_name='编号')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('note', models.TextField(blank=True, max_length=60, null=True, verbose_name='编号')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_test_code.partner', verbose_name='合伙人')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.IntegerField(verbose_name='开始时间')),
                ('to_time', models.IntegerField(verbose_name='结束时间')),
                ('state', models.CharField(blank=True, max_length=60, null=True, verbose_name='状态')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='for_test_code.developer', verbose_name='创业者')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_test_code.schedule', verbose_name='日程表')),
            ],
        ),
    ]
