# Generated by Django 3.2.14 on 2022-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleline',
            name='from_time',
            field=models.CharField(max_length=30, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='to_time',
            field=models.CharField(max_length=30, verbose_name='结束时间'),
        ),
    ]
