# Generated by Django 3.2.12 on 2022-02-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hasurauser_default_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCateogry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_router_path', models.CharField(max_length=200, verbose_name='路径')),
                ('frontend_router_name', models.CharField(help_text='对应前端router名称', max_length=200, verbose_name='类别')),
                ('frontend_router_redirect', models.CharField(blank=True, max_length=200, null=True, verbose_name='重定向path')),
                ('frontend_router_meta_title', models.CharField(max_length=200, verbose_name='类别')),
                ('frontend_router_meta_icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='显示图标')),
                ('rank', models.IntegerField(default=1, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_router_path', models.CharField(max_length=200, verbose_name='路径')),
                ('frontend_router_name', models.CharField(help_text='对应前端router名称', max_length=200, verbose_name='类别')),
                ('frontend_router_redirect', models.CharField(blank=True, max_length=200, null=True, verbose_name='重定向path')),
                ('frontend_router_meta_title', models.CharField(max_length=200, verbose_name='类别')),
                ('frontend_router_meta_icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='显示图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('rank', models.IntegerField(default=1, verbose_name='排序')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFunctionOperate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('rank', models.IntegerField(default=1, verbose_name='排序')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.RemoveField(
            model_name='hasurauser',
            name='default_group',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.AddField(
            model_name='hasurauser',
            name='organizations',
            field=models.ManyToManyField(to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='hasurauser',
            name='default_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.organization', verbose_name='默认机构'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('rank', models.IntegerField(default=1, verbose_name='排序')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('system_function_operates', models.ManyToManyField(to='api.SystemFunctionOperate', verbose_name='角色具有的权限')),
            ],
        ),
        migrations.AddField(
            model_name='hasurauser',
            name='default_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.role', verbose_name='默认用户组'),
        ),
        migrations.AddField(
            model_name='hasurauser',
            name='roles',
            field=models.ManyToManyField(to='api.Role'),
        ),
    ]
