# Generated by Django 3.2.12 on 2022-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220221_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
