# Generated by Django 3.2.12 on 2022-02-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220221_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functioncategory',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='systemfunction',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='systemfunctionoperate',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='functioncategory',
            name='parent_function_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.functioncategory', verbose_name='上级功能'),
        ),
        migrations.AlterField(
            model_name='role',
            name='system_function_operates',
            field=models.ManyToManyField(to='api.SystemFunctionOperate', verbose_name='角色具有的权限'),
        ),
        migrations.AlterField(
            model_name='systemfunction',
            name='function_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.functioncategory', verbose_name='所属类别'),
        ),
        migrations.AlterField(
            model_name='systemfunctionoperate',
            name='system_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operates', to='api.systemfunction', verbose_name='所属功能'),
        ),
    ]
