# Generated by Django 3.2.12 on 2022-03-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220309_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functioncategory',
            old_name='frontend_router_meta_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='functioncategory',
            old_name='frontend_router_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='systemfunction',
            old_name='frontend_router_meta_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='systemfunction',
            old_name='frontend_router_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='functioncategory',
            name='frontend_router_meta_title',
        ),
        migrations.RemoveField(
            model_name='functioncategory',
            name='frontend_router_path',
        ),
        migrations.RemoveField(
            model_name='functioncategory',
            name='frontend_router_redirect',
        ),
        migrations.RemoveField(
            model_name='systemfunction',
            name='frontend_router_meta_title',
        ),
        migrations.RemoveField(
            model_name='systemfunction',
            name='frontend_router_path',
        ),
        migrations.RemoveField(
            model_name='systemfunction',
            name='frontend_router_redirect',
        ),
    ]
