# Generated by Django 3.2.12 on 2022-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220327_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='parent_org',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='organization',
            name='position',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
