ALTER TABLE electric_power_sale_mthadjust
    ALTER  state SET DEFAULT 'draft',
    ALTER created_at SET DEFAULT Now(),
    ALTER updated_at SET DEFAULT Now();


ALTER TABLE electric_power_sale_mthadjustline
    ALTER previous_plan_common_mth_1 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_2 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_3 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_4 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_5 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_6 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_7 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_8 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_9 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_10 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_11 SET DEFAULT 0.0,
    ALTER previous_plan_common_mth_12 SET DEFAULT 0.0,

    ALTER adjust_plan_common_mth_1  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_2  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_3  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_4  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_5  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_6  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_7  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_8  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_9  SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_10 SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_11 SET DEFAULT 0.0,
    ALTER adjust_plan_common_mth_12 SET DEFAULT 0.0,

    ALTER previous_plan_flat_mth_1  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_2  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_3  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_4  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_5  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_6  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_7  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_8  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_9  SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_10 SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_11 SET DEFAULT 0.0,
    ALTER previous_plan_flat_mth_12 SET DEFAULT 0.0,

    ALTER adjust_plan_flat_mth_1  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_2  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_3  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_4  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_5  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_6  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_7  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_8  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_9  SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_10 SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_11 SET DEFAULT 0.0,
    ALTER adjust_plan_flat_mth_12 SET DEFAULT 0.0,

    ALTER previous_plan_valley_mth_1  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_2  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_3  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_4  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_5  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_6  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_7  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_8  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_9  SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_10 SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_11 SET DEFAULT 0.0,
    ALTER previous_plan_valley_mth_12 SET DEFAULT 0.0,

    ALTER adjust_plan_valley_mth_1  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_2  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_3  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_4  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_5  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_6  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_7  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_8  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_9  SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_10 SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_11 SET DEFAULT 0.0,
    ALTER adjust_plan_valley_mth_12 SET DEFAULT 0.0,

    ALTER previous_plan_peak_mth_1  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_2  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_3  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_4  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_5  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_6  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_7  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_8  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_9  SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_10 SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_11 SET DEFAULT 0.0,
    ALTER previous_plan_peak_mth_12 SET DEFAULT 0.0,

    ALTER adjust_plan_peak_mth_1  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_2  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_3  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_4  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_5  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_6  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_7  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_8  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_9  SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_10 SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_11 SET DEFAULT 0.0,
    ALTER adjust_plan_peak_mth_12 SET DEFAULT 0.0,

    ALTER  state SET DEFAULT 'draft';