# Generated by Django 3.2.12 on 2022-03-01 13:15

from django.db import migrations, models
import django.db.models.deletion
import electric_power_sale.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_systemfunctionoperate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='居间名称')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('agent_no', models.CharField(blank=True, max_length=60, null=True, verbose_name='编号')),
                ('toucher_1', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系人1')),
                ('toucher_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系人2')),
                ('toucher_mobile_1', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话1')),
                ('toucher_mobile_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话2')),
                ('default_agent_rate', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='默认居间分成比例')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization', verbose_name='上级机构')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('custom_no', models.CharField(blank=True, default=electric_power_sale.models.Customer.get_customer_no, max_length=60, null=True, verbose_name='客户编号')),
                ('toucher_1', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系人1')),
                ('toucher_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系人2')),
                ('toucher_mobile_1', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话1')),
                ('toucher_mobile_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话2')),
                ('grid_account', models.CharField(blank=True, max_length=60, null=True, verbose_name='电网账号')),
                ('grid_password', models.CharField(blank=True, max_length=60, null=True, verbose_name='电网密码')),
                ('elect_level', models.IntegerField(blank=True, null=True, verbose_name='电压等级')),
                ('transformer_volume', models.IntegerField(blank=True, null=True, verbose_name='变压器容量')),
                ('income_type', models.CharField(choices=[('income_type_rate', '按服务费率'), ('income_type_fixed', '按固定金额'), ('income_type_divide_rate', '按分成比例')], default='income_type_rate', max_length=40, verbose_name='收入结算方式')),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='服务费率')),
                ('fix_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='固定服务费')),
                ('divide_rate', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='分成比例')),
                ('agent_rate', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='与居间分成比例')),
                ('tax_diff', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='税差')),
                ('note_1', models.TextField(blank=True, null=True, verbose_name='备注1')),
                ('note_2', models.TextField(blank=True, null=True, verbose_name='备注2')),
                ('note_3', models.TextField(blank=True, null=True, verbose_name='备注3')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_power_sale.agent', verbose_name='所属居间')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization', verbose_name='上级机构')),
            ],
        ),
    ]
