# Generated by Django 3.2.12 on 2022-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0003_auto_20220302_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True, verbose_name='与居间分成比例'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='divide_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True, verbose_name='分成比例'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fix_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True, verbose_name='固定服务费'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True, verbose_name='服务费率'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_diff',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True, verbose_name='税差'),
        ),
    ]
