# Generated by Django 3.2.12 on 2022-03-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0004_auto_20220302_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='agent',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注1'),
        ),
    ]
