# Generated by Django 3.2.12 on 2022-03-09 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import electric_power_sale.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20220309_0900'),
        ('electric_power_sale', '0005_auto_20220303_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='合同名称')),
                ('contract_no', models.CharField(blank=True, max_length=40, null=True, verbose_name='合同编号')),
                ('contract_year', models.IntegerField(default=electric_power_sale.models.default_cur_year, verbose_name='所属年度')),
                ('contract_start_date', models.DateField(default=electric_power_sale.models.default_year_start_date, verbose_name='合同生效日期')),
                ('contract_end_date', models.DateField(default=electric_power_sale.models.default_year_end_date, verbose_name='合同结束日期')),
                ('contract_price_type', models.CharField(choices=[('price_type_common', '常规'), ('price_type_seprate_time', '分时段')], default='price_type_common', max_length=40, verbose_name='电价价方式')),
                ('price_common', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='常规时段电价(元/KWA)')),
                ('price_peak', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='峰时段电价(元/KWA)')),
                ('price_flat', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='平时段电价(元/KWA)')),
                ('price_valley', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='谷时段电价(元/KWA)')),
                ('state', models.CharField(default='draft', max_length=40, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注1')),
                ('created_at', models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
        ),
        migrations.CreateModel(
            name='MthAdjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mth', models.IntegerField(default=electric_power_sale.models.default_cur_mth, verbose_name='月份')),
                ('state', models.CharField(default='draft', max_length=40, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization', verbose_name='所属机构')),
            ],
        ),
        migrations.CreateModel(
            name='MthAdjustLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='draft', max_length=40, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization', verbose_name='所属机构'),
        ),
        migrations.CreateModel(
            name='MthAdjustLineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mth', models.IntegerField(default=electric_power_sale.models.default_cur_mth, verbose_name='月份')),
                ('previous_plan_common', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规')),
                ('previous_plan_flat', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段')),
                ('previous_plan_valley', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段')),
                ('previous_plan_peak', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段')),
                ('adjust_plan_common', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规')),
                ('adjust_plan_flat', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段')),
                ('adjust_plan_valley', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段')),
                ('adjust_plan_peak', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段')),
                ('state', models.CharField(default='draft', max_length=40, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('mth_adjust_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric_power_sale.mthadjustline', verbose_name='月度电量调整子表')),
            ],
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_power_sale.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='mth_adjust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric_power_sale.mthadjust', verbose_name='月度电量调整主表'),
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mth', models.IntegerField(default=electric_power_sale.models.default_cur_mth, verbose_name='月份')),
                ('plan_common', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规')),
                ('plan_flat', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段')),
                ('plan_valley', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段')),
                ('plan_peak', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段')),
                ('adjust_plan_common', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规')),
                ('adjust_plan_flat', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段')),
                ('adjust_plan_valley', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段')),
                ('adjust_plan_peak', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段')),
                ('act_common', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规')),
                ('act_flat', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段')),
                ('act_valley', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段')),
                ('act_peak', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段')),
                ('price_common', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='常规时段电价(元/KWA)')),
                ('price_peak', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='峰时段电价(元/KWA)')),
                ('price_flat', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='平时段电价(元/KWA)')),
                ('price_valley', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='谷时段电价(元/KWA)')),
                ('state', models.CharField(default='draft', max_length=40, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注1')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric_power_sale.contract', verbose_name='合同')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_power_sale.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization', verbose_name='所属机构'),
        ),
    ]
