# Generated by Django 3.2.12 on 2022-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0007_auto_20220309_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
