# Generated by Django 3.2.12 on 2022-03-12 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import electric_power_sale.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_power_sale', '0008_contract_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='created_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthadjust',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthadjust',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthagentbill',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthagentbill',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthagentbillline',
            name='created_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='mthagentbillline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='mthagentbillline',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthagentbillline',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthcustomerbill',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthcustomerbill',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthcustomerbillline',
            name='created_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='mthcustomerbillline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='mthcustomerbillline',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthcustomerbillline',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthdiffcustomerbill',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthdiffcustomerbill',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthdiffcustomerbillline',
            name='created_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='mthdiffcustomerbillline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='mthdiffcustomerbillline',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthdiffcustomerbillline',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthdraftcustomerbill',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthdraftcustomerbill',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='mthdraftcustomerbillline',
            name='created_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='mthdraftcustomerbillline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='mthdraftcustomerbillline',
            name='updated_at',
            field=models.DateTimeField(default=electric_power_sale.models.default_cur_datetime, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='mthdraftcustomerbillline',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
