# Generated by Django 3.2.12 on 2022-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0009_auto_20220312_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractline',
            old_name='act_common',
            new_name='act_common_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='act_flat',
            new_name='act_flat_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='act_peak',
            new_name='act_peak_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='act_valley',
            new_name='act_valley_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='adjust_plan_common',
            new_name='adjust_plan_common_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='adjust_plan_flat',
            new_name='adjust_plan_flat_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='adjust_plan_peak',
            new_name='adjust_plan_peak_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='adjust_plan_valley',
            new_name='adjust_plan_valley_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='plan_common',
            new_name='plan_common_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='plan_flat',
            new_name='plan_flat_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='plan_peak',
            new_name='plan_peak_mth_1',
        ),
        migrations.RenameField(
            model_name='contractline',
            old_name='plan_valley',
            new_name='plan_valley_mth_1',
        ),
        migrations.RemoveField(
            model_name='contractline',
            name='mth',
        ),
        migrations.RemoveField(
            model_name='contractline',
            name='price_common',
        ),
        migrations.RemoveField(
            model_name='contractline',
            name='price_flat',
        ),
        migrations.RemoveField(
            model_name='contractline',
            name='price_peak',
        ),
        migrations.RemoveField(
            model_name='contractline',
            name='price_valley',
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_common_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_flat_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_peak_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='act_valley_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='电量结算-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_common_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_flat_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_peak_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='adjust_plan_valley_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_common_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-常规'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_flat_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_peak_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='plan_valley_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_common_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_flat_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_peak_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='adjust_plan_valley_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='计划电量调整-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_common_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-常规'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_flat_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-平时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_peak_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-峰时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_11',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_12',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_6',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_7',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_8',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.AddField(
            model_name='mthadjustline',
            name='previous_plan_valley_mth_9',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='调整前计划电量-谷时段'),
        ),
        migrations.DeleteModel(
            name='MthAdjustLineDetail',
        ),
    ]
