# Generated by Django 3.2.12 on 2022-03-16 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0011_mthadjustline_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_no', models.CharField(max_length=40, verbose_name='电表号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注1')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric_power_sale.customer', verbose_name='关联客户')),
            ],
        ),
    ]
