# Generated by Django 3.2.12 on 2022-03-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0012_deviceno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mthcustomerbillline',
            name='contract_name',
        ),
        migrations.AddField(
            model_name='mthcustomerbillline',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_power_sale.contract', verbose_name='关联合同'),
        ),
    ]
