# Generated by Django 3.2.12 on 2022-03-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0013_auto_20220320_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mthagentbillline',
            name='plan_common',
        ),
        migrations.RemoveField(
            model_name='mthagentbillline',
            name='plan_flat',
        ),
        migrations.RemoveField(
            model_name='mthagentbillline',
            name='plan_peak',
        ),
        migrations.RemoveField(
            model_name='mthagentbillline',
            name='plan_valley',
        ),
        migrations.AddField(
            model_name='mthagentbillline',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_power_sale.contract', verbose_name='关联合同'),
        ),
        migrations.AddField(
            model_name='mthagentbillline',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_power_sale.customer', verbose_name='关联客户'),
        ),
    ]
