# Generated by Django 3.2.12 on 2022-03-21 14:23

from django.db import migrations, models
import electric_power_sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0014_auto_20220321_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mthagentbillline',
            name='agent_confirm_date',
            field=models.DateField(blank=True, default=electric_power_sale.models.default_cur_date, null=True, verbose_name='居间确认时间'),
        ),
    ]
