# Generated by Django 3.2.12 on 2022-03-27 02:54

from django.db import migrations, models
import electric_power_sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0015_alter_mthagentbillline_agent_confirm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认')], default='draft', max_length=40, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='elect_level',
            field=models.CharField(blank=True, choices=[('lt_1kv', '不满1千伏'), ('1kv_10kv', '1~10千伏'), ('35kv', '35千伏'), ('110kv', '110千伏'), ('220kv', '220千伏')], default='35kv', max_length=60, null=True, verbose_name='电压等级'),
        ),
        migrations.AlterField(
            model_name='mthadjust',
            name='mth',
            field=models.CharField(default=electric_power_sale.models.default_last_mth, max_length=7, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='mthagentbill',
            name='mth',
            field=models.CharField(default=electric_power_sale.models.default_last_mth, max_length=7, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='mthcustomerbill',
            name='mth',
            field=models.CharField(default=electric_power_sale.models.default_last_mth, max_length=7, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='mthdiffcustomerbill',
            name='mth',
            field=models.CharField(default=electric_power_sale.models.default_last_mth, max_length=7, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='mthdraftcustomerbill',
            name='mth',
            field=models.CharField(default=electric_power_sale.models.default_last_mth, max_length=7, verbose_name='月份'),
        ),
    ]
