# Generated by Django 3.2.12 on 2022-05-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_sale', '0017_contract_year_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='year_plan_flat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='年度签约电量-平(兆瓦时)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='year_plan_peak',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='年度签约电量-峰(兆瓦时)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='year_plan_valley',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='年度签约电量-谷(兆瓦时)'),
        ),
    ]
