version: 2
endpoint: http://hasura:8080
metadata_directory: 'metadata'
migrations_directory: 'migrations'
admin_secret: password
actions:
  kind: synchronous
  handler_webhook_baseurl: http://hasura:8080